### ISSUE TITLE
Error: Input file contains unsupported image format

### ISSUE THREAD

**Issue by vikmeup** [calibreapp/image-actions#11]
Based on https://github.com/trustwallet/assets/runs/221998657

Is there a way to ignore this error and continue the job and compress all the images? it sounds like it silently fail and does not produce any compressed images

Also, is there a way to know which images causes this issue? I can try to delete it to continue

**Comment by benschwarz** [comment]
Hey @vikmeup, thanks for logging this! 

I've just merged #12 which will log the erroneous file then continue processing. 

From using your images I wasn't able to find the problem image myself, so if you do please do share it with me. I'd love to include it in the test suite somehow. (Or be able to replicate the issue)

**Comment by benschwarz** [comment]
You'll need to kick off another run for trustwallet/assets

**Comment by vikmeup** [comment]
@benschwarz I believe those two images were causing an error, once we removed from the repo it started to work: https://github.com/trustwallet/assets/commit/149dc4b82d3fadd994589149f4f617e9eda82a94

**Comment by vikmeup** [comment]
@benschwarz also noticed that in this PR there was not comment from the action that images were compressed: https://github.com/trustwallet/assets/pull/203, was it a limitation from the Github comment length?

**Comment by benschwarz** [comment]
@vikmeup It might be, but I'd be surprised that the result got committed if the PR comment wasn't accepted. 

GitHub doesn't show me any 'checks' for trustwallet/assets#203, so I'm unable to check the log. Do you see an actions log for that PR?

**Comment by vikmeup** [comment]
@benschwarz also noticed https://github.com/trustwallet/assets/pull/216 this PR does not print anything. wonder that's wrong?

**Comment by benschwarz** [comment]
There's a log for that run. It reports an error: 

```
->> Generating markdown…
4225
->> Committing files…
4226
	 *  Head SHA: f0fe7481af51f6eaf0775c021335f94a1b79d002
4227
	 *  Tree 961aa5bd9c5bde9ce734a1f1d2d79d757cd00d06
4228
	 *  Converting images to blobs…
4229
(node:1) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
4230
    at response.text.then.message (/usr/local/src/image-actions/node_modules/@octokit/request/lib/request.js:56:27)
4231
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
4232
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
4233
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I wonder if you're also hitting an API request throttling error? (See calibreapp/image-actions#13)
