### ISSUE TITLE
Just a quick question!

### ISSUE THREAD

**Issue by 3kh0** [calibreapp/image-actions#113]
Does this work just like imgbot? It scans the base repo and opens a pr with the images all optimized? Did I get that correctly?

**Comment by benschwarz** [comment]
@3kh0 similar, but maybe a bit different. I've never used imgbot so I can't say directly. 

image-actions runs on YOUR PRs, searches for all images, optimises them and commits them back to your already open PR. If that's a workflow that sounds right, give it a shot on a test repo 👍

**Comment by 3kh0** [comment]
> @3kh0 similar, but maybe a bit different. I've never used imgbot so I can't say directly.
> 
> image-actions runs on YOUR PRs, searches for all images, optimises them and commits them back to your already open PR. If that's a workflow that sounds right, give it a shot on a test repo 👍

Ok thank you for answering my question! I will sure to give this a spin!
