### ISSUE TITLE
[Bug] `Input file contains unsupported image format` errors

### ISSUE THREAD

**Issue by chenrui333** [calibreapp/image-actions#119]
👋🏻 Hi there! This template will help you file a complete bug report for Image Actions, so one of the project owners can triage and respond to it promptly. Please fill relevant sections below and feel free to delete what does not apply to the issue you are seeing (including this comment).

Thank you for helping us improve Image Actions! ⚡️

***

## Describe the bug

`Input file contains unsupported image format` errors

```
Error:   [Error: Input file contains unsupported image format] <path>/temp.png
Error:   [Error: Input file contains unsupported image format] <path>/resources/brushed_antique_copper_diff.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/brushed_antique_copper_norm.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/brushed_antique_copper_ref.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/brushed_antique_copper_rough.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/brushed_antique_copper_spots_map.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/carbon_bump.png
Error:   [Error: Input file contains unsupported image format] <path>/resources/carbon_direction.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/carbon_reflectivity.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/example_roughness.png
Error:   [Error: Input file contains unsupported image format] <path>/resources/example_thumbnail.png
Error:   [Error: Input file contains unsupported image format] <path>/resources/example.png
Error:   [Error: Input file contains unsupported image format] <path>/resources/metal_diamond_pattern_diamond_plate_diamond_plate_brushing_norm.jpg
Error:   [Error: Input file contains unsupported image format] <path>/resources/metal_diamond_pattern_diamond_plate_diamond_plate_bumps_norm.jpg
```

## Expected behaviour

Should compress images fine

## Screenshots
If applicable, add screenshots to help explain the problem.

## Additional context
Add any other context about the issue you’re seeing.

**Comment by benschwarz** [comment]
Hey @chenrui333, we'll need a bit more information before we're able to diagnose this issue. If you can fill out the issue template we'll be able to assess and advise from there.

**Comment by chenrui333** [comment]
it seems fine, with this PR, https://github.com/chenrui333/github-action-test/pull/48

I am bit lost. @benschwarz can you give me some hints about how to test compression in my local?

**Comment by chenrui333** [comment]
@benschwarz actually check on [this run](https://github.com/chenrui333/github-action-test/runs/5580640846):

> Error:   [Error: Input file contains unsupported image format] /github/workspace/public/images/temp.png

**Comment by chenrui333** [comment]
Actually the files might be wrong. Close the issue and checking on my side.
