### ISSUE TITLE
[Feature Request] Can we have that  command line utility for the same ?

### ISSUE THREAD

**Issue by ykhandelwal913** [calibreapp/image-actions#124]
### What problem would this feature solve?

If we have command line utility, we will be able to run that in local and get the results in local before committing to github.

### Describe the solution you’d like to see

A command line option with all the options you are adding in github actions

### Are you willing to work on implementing this solution?

No

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
@ykhandelwal913 You could potentially solve your use case by running `image-actions` from your command line via docker. While it's 100% ok to use this repository for that purpose, it isn't a use case that we're actively or mindfully considering. This isn't a feature we're interested in supporting. Seeing as you've marked that you're not willing to work on this feature request, I'll go ahead and close this.
