### ISSUE TITLE
[Feature Request] Make a recent release with tag instead of `main` 

### ISSUE THREAD

**Issue by bobmaerten** [calibreapp/image-actions#128]
### What problem would this feature solve?

When running the action with the latest release, we have this warning message :

`Update required: Update image-actions configuration to the latest version before 1/1/21. See README for instructions.`

Unlike what is stated in the README, I'm not willing to use `calibreapp/image-actions@main` definition for the action, as I don't want to have to check all the changes introduced in every commit in the main branch for an action that will run on my repos. Checking for code and behavior for a fixed release would be far more secure and efficient.
Also, it's a common security recommendation NOT to use a branch for a GitHub Action, as it may introduce some failures or unwanted behaviors when calling the action.

A similar idea was evoked in #123 but seems not having been applied.

### Describe the solution you’d like to see

Fixing a stable action behavior within a release, as previously made until [1.1.0](https://github.com/calibreapp/image-actions/releases/tag/1.1.0).

### Are you willing to work on implementing this solution?

No, as it's not actionnable for a non-contributor.

### Describe alternatives you’ve considered

The alternative would be to check code/behavior a recent version and stick to this SHA-1 version in our GH workflows.

### Additional context

I'm using this action in a private repo.

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by kdeldycke** [comment]
Latest tagged release is `v1.1.0` which is dated back to January 2020. Is there any plan to cut a new release?
