### ISSUE TITLE
Rate limit error

### ISSUE THREAD

**Issue by mattstratton** [calibreapp/image-actions#13]
This doesn't seem to work well on a large repo (we have many, many images in our repo for [devopsdays/devopsdays-web](https://www.github.com/devopsdays/devopsdays-web). When we run the action, it eventually errors at the end with:

```
	 *  Head SHA: cdf0db10952ecef99e62678e452c9d6bd7dc014b
	 *  Tree 8a59b30c851ab4107af8c85f0d66fae9d2892257
	 *  Converting images to blobs…
(node:1) UnhandledPromiseRejectionWarning: HttpError: API rate limit exceeded for installation ID 1908306.
    at response.text.then.message (/usr/local/src/image-actions/node_modules/@octokit/request/lib/request.js:56:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
https://github.com/devopsdays/devopsdays-web/pull/8274/checks?check_run_id=222210418#step:4:7317 for reference. Or https://github.com/devopsdays/devopsdays-web/runs/222210418

**Comment by benschwarz** [comment]
Thanks for logging @mattstratton. I must say I never expected to be calling the API enough to hit the limit! 

It appears that the API limitation occurs because we're calling `createBlob` to create the object for each newly optimised image. 

From looking at the [GitHub docs](https://developer.github.com/v3/#rate-limiting) there should be 5K requests per user (I'm guessing actions counts as a user?). 

I guess the most reliable thing we could do for image-actions is to use the git command line client and commit it rather than using the API.

**Comment by adrianmoisey** [comment]
Another option is to only compress/process the images that have been added or modified, and not the entire repo.

**Comment by benschwarz** [comment]
@adrianmoisey thats what we do. Only changed files are committed

**Comment by mattstratton** [comment]
Huh that’s so weird. In the example where we hit the rate limit that pr didn’t include any image files. 

Maybe there’s a confusion - i think Adrian meant only run the analysis and compression in files changed by the PR.

**Comment by benschwarz** [comment]
@mattstratton Thanks for clarifying. I had missed what Adrian meant. 

Unfortunately, if you only compressed images that were changed in the current PR, then you'd end up with existing images that are never processed. Seems like we should use a real git client and avoid the API for this 👍

**Comment by benschwarz** [comment]
If anyone has this issue can you please upvote this comment to let us know? Otherwise we'll close this issue.
