### ISSUE TITLE
Default settings are not lossless?

### ISSUE THREAD

**Issue by coliff** [calibreapp/image-actions#14]
It appears that the default settings are not lossless. I ran this action on a private repo with some already losslessly optimized images (via ImageOptim for MacOS) and it reduced the filesizes and quality of most of the images. In the 'image-actions' settings it says the default settings are:
```
jpeg:
  quality: 80
png:
  quality: 80
```
if that is indeed lossless then what would changing those numbers to 100 do?

According to: http://sharp.pixelplumbing.com/en/stable/api-output/#jpeg and http://sharp.pixelplumbing.com/en/stable/api-output/#png the lossless setting is off by default.

**Comment by benschwarz** [comment]
Hey @coliff, thanks for raising this. 

I've been meaning to update the readme to mention that the default settings will offer near-lossless, but all the same good webby defaults for most deployments. Apart from that we could probably visually show some put images at various levels of quality so people are able to see what they can get. 

If you'd like to reverse out the changes that image-actions made to your PR, don't forget there's the `git revert <sha>` command to do just that. 👍

**Comment by coliff** [comment]
thanks for the quick reply :-)  At the top of the README it says 'Compression is fast, efficient and lossless'.
To be honest, I personally think the default settings should be lossless - I think that's what would be expected. That's what the GitHub App '[ImgBot](https://imgbot.net/)' does and other 3rd party services I've seen do. Reducing the quality of the images can introduce problems, for example if an image was copied to another repo with Calibre image-actions enabled it'd further reduce the quality again.
No probs on the personal repo I made that PR on, I didn't merge it. I'm testing now to see if I can set it to lossless via the settings.

**Comment by benschwarz** [comment]
@coliff We've updated the readme to show what the default settings are and how to change them. Let me know if there's anything we can do to help on this.
