### ISSUE TITLE
[Feature Request] Support on-premise github enterprise

### ISSUE THREAD

**Issue by kiissaac** [calibreapp/image-actions#162]
### What problem would this feature solve?

image-actions is very useful action,
but in our company,
unfortunately we have to modify some code and rebuild docker image

This is because the api url is fixed toward github.com

If you use `GITHUB_API_URL` action variable in `octokit`,
not only me but also many enterprise github users will be very happy

https://docs.github.com/en/actions/learn-github-actions/variables

### Describe the solution you’d like to see

1. export `GITHUB_API_URL` in [constants.ts](https://github.com/calibreapp/image-actions/blob/main/src/constants.ts)
2. use `GITHUB_API_URL` in [github-api.ts](https://github.com/calibreapp/image-actions/blob/main/src/github-api.ts)
like below
```
...
const octokit = new Octokit({ auth: `token ${GITHUB_TOKEN}`, baseUrl: `${GITHUB_API_URL}` })
...
```

may be that all.

### Are you willing to work on implementing this solution?

Yes

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
@kiissaac Sounds good to me — do you have bandwidth to pick up this change? We'd happily help get your PR through and released.

**Comment by kiissaac** [comment]
@benschwarz 
Yes, we try it.
Thank you for giving us a chance.
My team member will support this.
