### ISSUE TITLE
[Bug] WebP optimization requires successive passes to optimize

### ISSUE THREAD

**Issue by mastercoms** [calibreapp/image-actions#164]
### Describe the bug

Hi, I'm receiving successive PRs to optimize webp images that each reduce the file size. Can this be done in one pass instead?

Occurrence 1:

https://github.com/mastercomfig/hud-db/pull/7
https://github.com/mastercomfig/hud-db/pull/8
https://github.com/mastercomfig/hud-db/pull/9

Occurrence 2:

https://github.com/mastercomfig/hud-db/pull/11
https://github.com/mastercomfig/hud-db/pull/12
https://github.com/mastercomfig/hud-db/pull/13
https://github.com/mastercomfig/hud-db/pull/14

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
cwebp has a `--passes` argument, but that doesn't appear to be translated into [Sharp's documentation](https://sharp.pixelplumbing.com/api-output#webp). At the moment, I think the answer is no.
