### ISSUE TITLE
[Feature Request] How to get it to optimize images that are already inside the repo?

### ISSUE THREAD

**Issue by kuwts** [calibreapp/image-actions#173]
### What problem would this feature solve?

Image optimization for images that are already inside the repo when the action was added.

### Describe the solution you’d like to see

Image optimization for images already in the repo

### Are you willing to work on implementing this solution?

Yes

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Hey @kuwts, that's what image-actions does by default. All previous images will be processed, but the default configuration requires that an image file is changed in your PR. 

You could remove this section of the configuration: 

```
paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
```
