### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by vpicone** [calibreapp/image-actions#18]
Even after the action has been merged into master, subsequent PR's fail silently when processing:

```
    - Processing: /github/workspace/static/videos/motion/motion-style-expressive.jpg
    - Processing: /github/workspace/static/videos/motion/motion-style-insitu.jpg
->> Generating markdown…
->> Committing files…
	 *  Head SHA: c7d4a5f6eb23c468850cc77dbc13a369e0e07d1d
	 *  Tree 2737fa5f107a598c0fc1d6a196d8725e5223fd2f
	 *  Converting images to blobs…
(node:1) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at response.text.then.message (/usr/local/src/image-actions/node_modules/@octokit/request/lib/request.js:56:27)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

[Example run](https://github.com/carbon-design-system/design-language-website/pull/315/checks?check_run_id=259741433)

**Comment by benschwarz** [comment]
@vpicone Thanks for logging this. I ran it over some test PRs this morning and did not see such an issue. It might be possible that there was an issue with the GitHub API at the time, but a little hard to tell from the logging of the error. 

Would you be able to take it for another spin to check this wasn't just a blip?

**Comment by vpicone** [comment]
@benschwarz still getting the same error. Seems like the strategy for committing to a branch might not be supported 100% anymore? Also seeing the same failure to commit in repositories where the action was previously working so I'm pretty sure it's not a repo permissions/config thing.

**Comment by vpicone** [comment]
@benschwarz hmm, looks like it's working again! I'll close this for now.

**Comment by benschwarz** [comment]
@vpicone Whew! 😌

I was becoming concerned that GitHub had changed something and broken the action. Glad to hear it's working out atm. Let me know if that changes. 👍

**Comment by ericcornelissen** [comment]
I'm not 100% sure this is the same scenario, but I'm pretty sure it is. I'm seeing the exact same error as described in the original post [in this run of the action](https://github.com/ericcornelissen/simple-icons/runs/453612767#step:4:21).

The only possible difference between my scenario and the original scenario, I can think of, is that the person making the Pull Request is not in any way part of the repository. Whereas vpicone might (have been) a part of [carbon-design-system/design-language-website](https://github.com/carbon-design-system/design-language-website) (_a confirmation in this regard would be helpful_).

**Comment by benschwarz** [comment]
@ericcornelissen Hmm. Curious. (I think) I've only seen this error after a lot of files have been processed / committed.

I wonder if updating our commit method to use `octokit.repos.createOrUpdateFile()` will reduce the number of API requests sufficiently enough? 🤔

**Comment by ericcornelissen** [comment]
> Hmm. Curious. (I think) I've only seen this error after a lot of files have been processed / committed.

Not sure if that is the problem in my case @benschwarz. The target branch contains just 3 images and the source branch contains just a single image...

**Comment by rajbos** [comment]
Found these results:

|Check|Results|
|---|---|
|CodeQL on the forked repo|${codeQLSymbol}|

:robot:

**Comment by rajbos** [comment]
Found these results:

|Check|Results|
|---|---|
|CodeQL on the forked repo|${codeQLSymbol}|

:robot:

**Comment by rajbos** [comment]
Found these results:

|Check|Results|
|---|---|
|CodeQL on the forked repo|${codeQLSymbol}|

:robot:

**Comment by rajbos** [comment]
Found these results:

|Check|Results|
|---|---|
|CodeQL on the forked repo|${codeQLSymbol}|

:robot:
