### ISSUE TITLE
Resizing Images

### ISSUE THREAD

**Issue by Fishwaldo** [calibreapp/image-actions#20]
Would be awesome if there was a option to resize images as well.

**Comment by benschwarz** [comment]
@Fishwaldo How would you see this working? I think you'd want to be able to specify a rule for a given directory / path.

That way you could, for example say `/images/avatars` should always be a cropped square at 300x300.

**Comment by Fishwaldo** [comment]
Yeah - essentially that’s the way I see it working. In my case we have a directory full of user contributed pics. We currently have a manual process to resize them after committing. Would be perfect to do this automatically!

**Comment by benschwarz** [comment]
Sounds useful, but atm we don't have the bandwidth to add a huge new feature that changes the library so dramatically. 

If someone would like to take a shot at implementing this, I'd be more than happy to work through it together.

**Comment by benschwarz** [comment]
Closing due to lack of interest. If you're interested in image-actions having this capability or able to help put it together, please let us know. 👍
