### ISSUE TITLE
Re-compress an already-compressed image issue?

### ISSUE THREAD

**Issue by chenrui333** [calibreapp/image-actions#23]
One feedback that I got is whether this github action is potentially going to re-compress the already-compressed images. 

I am curious about what are your thoughts on it.

**Comment by chenrui333** [comment]
I filed a couple of PRs this afternoon, seems working pretty well so far.

**Comment by chenrui333** [comment]
Sorry for spamming the repo with some many issues, so far I think it works well for us.

**Comment by hugovk** [comment]
See https://github.com/hugovk/python-logos/pull/1 for an example where lots of images are compressed when the PR is opened, and then one image is re-compressed when another commit is pushed, making it look worse: https://github.com/hugovk/python-logos/pull/1#issuecomment-552117733.

**Comment by benschwarz** [comment]
@chenrui333 @hugovk Because image-actions does not store state information about images, they're always compressed — if there's a significant improvement (more than -1%), the image will be committed, otherwise ignored. 

That way, if subsequent commits update the same image, it'll be reevaluated and committed if need be.

**Comment by hugovk** [comment]
How about an option to only compress images that are changed in a PR?

We'd need a way to do a first pass, but after that, it would only check the modified files.

The recompression and quality loss in https://github.com/hugovk/python-logos/pull/1#issuecomment-552117733, coupled with https://github.com/calibreapp/image-actions/issues/25, is unfortunately enough not to use the action.

**Comment by benschwarz** [comment]
If that was the case pre-existing images in a repo would never be processed.

**Comment by hugovk** [comment]
Yep, hence a needing a way to do a first pass.

**Comment by benschwarz** [comment]
> The recompression and quality loss in hugovk/python-logos#1 (comment), coupled with #25, is unfortunately enough not to use the action.

Let's assume both #25 and hugovk/python-logos#1 are fixed. They seem like bugs and will be treated as such.
