### ISSUE TITLE
Feature Request: Add support for gif

### ISSUE THREAD

**Issue by chenrui333** [calibreapp/image-actions#37]

**Comment by benschwarz** [comment]
Thanks for logging this @chenrui333. I'm not quite sure where we'd start with GIF compression to be honest. It's almost never the best image format for motion graphics. 

Any effort that would be made to better compress a GIF would be to drop the framerate, or reduce the colour palette or other lossy enhancements. 

That doesn't feel like something you'd set and forget for a whole repo (without being able to configure it a lot), which is kind of the whole point of image-actions. 

What do you think about all that?

**Comment by benschwarz** [comment]
Closing due to lack of feedback, feel free to re-start the conversation

**Comment by chenrui333** [comment]
Yeah, sorry for getting back late on this. I am less familiar with the image compression tooling than I should, we were using  imagemin-lint-staged plugin (which does gif impression) before, so I was curious whether it would be possible to add gif support in here.

Let me know if that makes more sense.

**Comment by manovotny** [comment]
I stumbled in here looking for GIF support, which is offered by [another GitHub Action](https://github.com/marketplace/actions/image-optimizer), but I wasn't looking too add another monthly subscription to use their underlying API service (only 25MB on the free tier). 

If this were to be attempted at all, using [gifsicle](https://github.com/kohler/gifsicle) would likely be the path forward. It's what powers GIF optimization in [ImageOptim](https://github.com/JamieMason/ImageOptim-CLI), [Gifski](https://github.com/sindresorhus/Gifski), and soon probably [Kap](https://github.com/wulkano/kap) too.

**Comment by chenrui333** [comment]
I will reopen a new one.

**Comment by benschwarz** [comment]
@manovotny Yep, gifsicle is likely the way forward for GIF support. That's what we'd use 👍

Anyone interested in picking up this work? 

---

Thanks to alerting us to that GitHub action, they'd copied parts of image-actions and not followed the correct license procedures 👎

**Comment by manovotny** [comment]
> they'd copied parts of image-actions and not followed the correct license procedures

Oh no! That's terrible! A 👎indeed!

**Comment by benschwarz** [comment]
Closing due to lack of movement
