### ISSUE TITLE
Docker run failed with exit code 78

### ISSUE THREAD

**Issue by ericnkatz** [calibreapp/image-actions#40]
Not sure if this is something to do with my images but having an issue where this action is failing with `##[error]Docker run failed with exit code 78`

We don't often add images to PRs so I'm not sure how typical this type of failure is.

In the past, the action has definitely worked as anticipated without failing.

Thanks for maintaining this! ❤️ 

![image](https://user-images.githubusercontent.com/91019/72165122-ecd85b80-3394-11ea-924d-7e92b6ddef59.png)

**Comment by ericnkatz** [comment]
Could this be related to #29 ?

**Comment by benschwarz** [comment]
Hey @ericnkatz, 

I believe this error/warning is because image-actions only expects to be run for pull requests. Did you maybe enable it for `push` rather than `pull_request`? (Feel free to post your workflow.yml file!)

**Comment by ericnkatz** [comment]
> Hey @ericnkatz,
> 
> I believe this error/warning is because image-actions only expects to be run for pull requests. Did you maybe enable it for `push` rather than `pull_request`? (Feel free to post your workflow.yml file!)

This was absolutely the problem. Not sure if we got overzealous when we updated some of our actions but on `pull_request` and everything is kosher again.

Thanks!
