### ISSUE TITLE
Feature Request: Add support for gif

### ISSUE THREAD

**Issue by chenrui333** [calibreapp/image-actions#48]
https://github.com/calibreapp/image-actions/issues/37#issuecomment-582730993

> I stumbled in here looking for GIF support, which is offered by [another GitHub Action](https://github.com/marketplace/actions/image-optimizer), but I wasn't looking too add another monthly subscription to use their underlying API service (only 25MB on the free tier).
> 
> If this were to be attempted at all, using [gifsicle](https://github.com/kohler/gifsicle) would likely be the path forward. It's what powers GIF optimization in [ImageOptim](https://github.com/JamieMason/ImageOptim-CLI), [Gifski](https://github.com/sindresorhus/Gifski), and soon probably [Kap](https://github.com/wulkano/kap) too.

**Comment by benschwarz** [comment]
Let's stick with #37
