### ISSUE TITLE
A little question: the integration action that never ends

### ISSUE THREAD

**Issue by usagi-f** [calibreapp/image-actions#52]
Hi, I have a question and want to your opinion.

Now I'm using the Amplify Console by AWS. This is executed related to the pull request and start the AWS environment. So that is behaving as the Github integration on PR.

![image](https://user-images.githubusercontent.com/9045135/80456604-d74d6880-8968-11ea-8118-6c933d1d787a.png)

In the Image Actions, it automatically add the commit by bot. However, somehow it won't end integrate progress only when this commit.

![image](https://user-images.githubusercontent.com/9045135/80456630-e502ee00-8968-11ea-80f9-df62e05248bf.png)

The strange thing is that even though the operation is completed successfully on the AWS console screen, Actually it's still displayed as in progress on Github.

![image](https://user-images.githubusercontent.com/9045135/80456668-f64bfa80-8968-11ea-8317-d50b3ffc1f43.png)

I can't isolate that the problem point is Github platform, AWS or this.

If you know anything, please response.
If you no idea, would you close this issue. no problem :)

 Thank you.

**Comment by benschwarz** [comment]
Hey @usagi-f, are you able to provide any logs from GitHub actions?

**Comment by usagi-f** [comment]
@benschwarz 
Thank you quick response!

There is no problem with the compression process itself.
![image](https://user-images.githubusercontent.com/9045135/80457060-a3bf0e00-8969-11ea-9386-177dc240d3bf.png)

And, execution log on the AWS side has also ending without any problems :(

**Comment by benschwarz** [comment]
@usagi-f In that case, I'd say it looks like a GitHub Actions issue — Maybe try contacting their support.

Let me know how you go!

**Comment by usagi-f** [comment]
Thank you. I will refer to your advice. 👍
