### ISSUE TITLE
feature request: setting progressive option in jpeg?

### ISSUE THREAD

**Issue by thisguychris** [calibreapp/image-actions#56]
Hi, 👋

Thanks for making this GitHub action. I'm trying this out to use in our organization.

I was looking for a way to turn on progressive jpeg because I think it'll have a [comeback with http2](https://blog.cloudflare.com/parallel-streaming-of-progressive-images/). 

While `webp` can give the smallest of file size, it doesn't support progressive or interlaced mode by jpeg. Where you can just send 10 to 20% of the file and your users visually see the whole image.

I believe it's supported by the dependency under the hood it's just a matter of exposing the option? Let me know if this is something we can add, I can help with a PR if needed.

**Comment by benschwarz** [comment]
Hey @thisguychris! 

Thanks for logging this. I agree, this would be a welcome addition to image-actions. 

Under the covers, image-actions uses sharp to process images. As you'll see from the [jpeg output options](https://sharp.pixelplumbing.com/api-output#jpeg), progressive mode can be turned on using a boolean flag. 

GitHub actions configuration is a little annoying in that it only accepts string keys to `action.yml` (more complex objects like hashes are not possible), so the way to implement this would be to add a configuration option to `action.yml`, add a default value to `constants.js` and wire it through in `config.js`. 

Do you think you'd like to take a shot at implementing and documenting this option?

**Comment by thisguychris** [comment]
Hey @benschwarz sorry I missed your reply yesterday.

Yes, I would love to take a shot. I'll work on this now and will ping you if I get stuck.

**Comment by benschwarz** [comment]
Sure thing! Let me know if you have any queries ✌️

**Comment by thisguychris** [comment]
@benschwarz please have a look: https://github.com/calibreapp/image-actions/pull/57
