### ISSUE TITLE
Change "near-lossless compression" to "high quality compression" or something similar

### ISSUE THREAD

**Issue by nabati** [calibreapp/image-actions#62]
I think writing "near-lossless compression" is a bit misleading. Compression can either be lossless or lossy, there is no "near-lossless", that's called lossy compression. It seems like the defaults are lossy, so I would either clarify that "near lossless-compression" is actually "high quality lossy compression" or something similar. 

What do you think?

**Comment by benschwarz** [comment]
I don't find the language used to be misleading.

As you've pointed out compression can be lossless or lossy.  To me, "near-lossless" implies that there's almost no visual difference between images after image-actions has been run. 

With the default settings, this is true. There's an acceptable and very minor reduction in image quality. I think it's reasonable that the marketing bullet points explaining what image-actions does as a very high level uses descriptive and easy to grok language. 

Thanks for raising the question. All the same, I'm happy with where it's at 👍
