### ISSUE TITLE
Feature Request: Add SVGO

### ISSUE THREAD

**Issue by majouji** [calibreapp/image-actions#7]
Adding SVGO support to optimize SVG files would be great! Warning that SVGO can break SVG font files however.

**Comment by kaelig** [comment]
>In my experience SVGO often mangles important details in SVG assets and it’s not something I’d ever automate without being able to easily review and confirm.

It can take out important details, but in the case of an icon library like https://github.com/Shopify/polaris-icons, we're looking to automate optimization at the PR level, enabling humans to approve the optimized version (we have a custom SVGO config, and run it on icons at build time).

Would you accept a pull request, by any chance?

**Comment by benschwarz** [comment]
@kaelig Thanks for offering to help! Great to hear you've been making use of image-actions too 🎈 

I'd _totally_ accept a pull request. Here's a couple of thoughts: 

* One thing that worries me (maybe needlessly) is that the default options for SVGO alter SVGs a little too much for comfort. Do you have a set of default options that you'd call "safe" to include? 
* Maybe we could disable SVG optimisation by default. We'd need to add an explanation to enabling it in `README.md`. (If we think that the defaults are dangerous to add?)

**Comment by kaelig** [comment]
Fab! I agree on disabling SVG optimization by default. It's a lossy operation that is undesirable in most cases. 

When it comes to the config, how about starting with the default one, and let the user provide an alternative one? This way, you can delegate all config-related issues to SVGO?

**Comment by benschwarz** [comment]
Sounds good to me. To recap: 

- Yes, let's disable it by default
- Let's use the default SVGO config
- Let's demonstrate how to enable SVGO (and set it's config options) to the readme section for  `.github/calibre/image-actions.yml`

Have you thought about how to handle turning SVGO off by default? 

It could maybe be done like this: 

```yml
ignorePaths:
  - "node_modules/**"
  - "*.svg"
```

Interested to hear your take on that though.

**Comment by kaelig** [comment]
>Have you thought about how to handle turning SVGO off by default?

Is it possible to have an opt-in flag in the action's settings?

**Comment by benschwarz** [comment]
> Is it possible to have an opt-in flag in the action's settings?

Yep. I'd add an `enabledOptimisations ` key to the [default config](https://github.com/calibreapp/image-actions/blob/master/src/config.js#L18-L23):

```js
{
  enabledOptimisations: ['jpeg', 'png', 'webp'],
  jpeg: { quality: 80 },
  png: { quality: 80 },
  webp: { quality: 80 },
  svg: {  }, // #opts to be sent to svgo
  ignorePaths: ["node_modules/**"]
}
```

Users would then be able to override the default by creating a [`.github/calibre/image-actions.yml`](https://github.com/calibreapp/image-actions#configuration) with: 

```yml
enabledOptimisations: 
  - jpeg
  - png
  - webp
  - svg
```

How's that sound?

**Comment by kaelig** [comment]
Would you be open to something like that, by any chance?

```js
const defaultConfig = {
  ignorePaths: ["node_modules/**"],
  jpeg: { enabled: true, options: { quality: 80 }, ignorePaths: null },
  png:  { enabled: true, options: { quality: 80 }, ignorePaths: null },
  webp: { enabled: true, options: { quality: 80 }, ignorePaths: null },
  svg:  { enabled: false, options: null, ignorePaths: null },
};
```

**Comment by benschwarz** [comment]
@kaelig Before I edited it out, that's what my suggestion was going to be. 

I think the biggest problem with changing the existing config schema is that anyone who has an existing custom config in place would then not have the options passed correctly.

**Comment by kaelig** [comment]
>I think the biggest problem with changing the existing config schema is that anyone who has an existing custom config in place would then not have the options passed correctly.

This call is definitely up to you, I can see how the users of this action might not expect a breakage in their config…

**Comment by benschwarz** [comment]
@kaelig I think `enabledOptimisations` is the way to go 👍

**Comment by benschwarz** [comment]
Hey @kaelig, just checking in. Did you have any progress to share with this? LMK if I can help somehow. Otherwise I might take a stab at this towards the end of the year.

**Comment by kaelig** [comment]
Hey Ben! Haven't had time yet, so please don't hesitate to go first :)
