### ISSUE TITLE
New compressOnly pull request method commits images that get bigger

### ISSUE THREAD

**Issue by bazzadp** [calibreapp/image-actions#76]
@benschwarz looks like there's a problem with the new compressOnly and pull request option we recently added.

I've just done some testing on my own repo and it compressed, and opened a PR with all the changed files as expected. Unfortunately however nearly all the files grew in size! Think these are images I'd optimised outside of calibre action so guessing that optimised them a bit differently/more efficiently. [Example run here](https://github.com/bazzadp/almanac.httparchive.org/runs/1118382918?check_suite_focus=true).

I was under the (perhaps mistaken!) belief that the image files would only be overwritten if they were smaller but guess that's not the case? If so we need to rethink this, as the create pull request sweeps up ALL files that have been changed, whether bigger or smaller, and if there are any then creates a pull request.

We should probably remove the advice to use create-pull-request from the README for now to prevent people increasing images sizes.

**Comment by benschwarz** [comment]
To mitigate this, I think we could perform the following changes: 

* Processed files into to `/tmp/image-actions`
* Compare the byte size report of the original image against the processed edition
* Filter by images that are smaller, perform a `cp` to replace the original with the processed edition

Sound good? Any other thoughts to share here?

**Comment by bazzadp** [comment]
It's not as simple as #77 is it?

How can I test this btw? I've managed to compile the typescript and run `npm run test` and also built the Dockerfile but how can I then use that Dockerfile to actually test this change before and after?

**Comment by benschwarz** [comment]
> It's not as simple as #77 is it?

Ah! To be honest I didn't check the implementation before I wrote this. I assumed we straight up overwrote files, but instead they're copied to an intermediate buffer. Too easy 🤹🏻‍♂️ #77 will work 👍

**Comment by benschwarz** [comment]
> How can I test this btw? I've managed to compile the typescript and run `npm run test` and also built the Dockerfile but how can I then use that Dockerfile to actually test this change before and after?

I'll share (and document) a `docker-compose` workflow during my day tomorrow. 👍

**Comment by bazzadp** [comment]
Excellent - just tested it there and seems to work - assuming you released it and I didn't mess up my testing :-)

Thanks - great to still have this functionality!
