### ISSUE TITLE
[Feature Request] Compress based on commit rather then pull request

### ISSUE THREAD

**Issue by Macleykun** [calibreapp/image-actions#91]
## What problem would this feature solve?
I've made a workflow to convert all images to WEBP, and noticed we can futher compress those images to get AVIF levels of compression. However, we do everything based on commit and pull.

So when developer adds some images in their commit, it will be converted to webp and then compressed. However image-actions doesn't seem to work in this regard. I haven't been able to find anything where it can do this based on commit level.

If possible, i would love to see it being able to scan the current files, compress them, and leave it be, so that i can push them in the workflow so that everything is converted and compressed.

Basicly an option to not make a pullrequest and just compress and leave them be withoud breaking.

**Comment by bazzadp** [comment]
Have a look at the [`compressOnly`](https://github.com/calibreapp/image-actions#run-compression-only) flag.

You'll then need to manually push these changes or open a new PR for these.

See examples here of how to use it:
- [Compress on schedule (or on demand)](https://github.com/calibreapp/image-actions#compress-on-demand-or-on-schedule)
- [Compress from PR from forked repo](https://github.com/calibreapp/image-actions#process-pull-requests-from-forked-repositories) (be default GitHub Actions can't add to PRs from forks).

**Comment by Macleykun** [comment]
So i tried the compressOnly flag but recieved this error:
`Run calibreapp/image-actions@main
/usr/bin/docker run --name ghcriocalibreappimageactionsimageactionsmain_72d217 --label cc4956 --workdir /github/workspace --rm -e pythonLocation -e LD_LIBRARY_PATH -e INPUT_GITHUBTOKEN -e INPUT_COMPRESSONLY -e INPUT_JPEGQUALITY -e INPUT_JPEGPROGRESSIVE -e INPUT_PNGQUALITY -e INPUT_WEBPQUALITY -e INPUT_IGNOREPATHS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/VoxSiren.github.io/VoxSiren.github.io":"/github/workspace" ghcr.io/calibreapp/image-actions/image-actions:main
/usr/local/src/image-actions/node_modules/sharp/lib/constructor.js:32
  throw new Error(error);
  ^

Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/usr/local/src/image-actions/node_modules/sharp/lib/constructor.js:32:9)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/src/image-actions/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)`
Is this an error on my side or internally?
Workflow used: https://github.com/Macleykun/VoxSiren.github.io/blob/main/.github/workflows/webpconverter.yml

**Comment by bazzadp** [comment]
Syntax looks right. I notice the following [in your logs](https://github.com/Macleykun/VoxSiren.github.io/runs/1727543280?check_suite_focus=true):

```
Run calibreapp/image-actions@main
  with:
    githubToken: ***
    compressOnly: true
    jpegQuality: 80
    jpegProgressive: false
    pngQuality: 80
    webpQuality: 80
    ignorePaths: node_modules/**
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.1/x64/lib
```

I don't have those last two when I use this, so I wonder if that `LD_LIBRARY_PATH` variable is breaking things? Maybe need to unset that?

Might be worth removing the Python (and WebP) parts and seeing if it works, then add them back in with an LD_LIBRARY_PATH reset.

**Comment by Macleykun** [comment]
Yep, after thinkering with it more, i got it to work fully.
Had to specify the normal LD_LIBRARY_PATH in the job env.

Wasn't to sure what compression only actually meant, but it's obviously clear!

Thank you for all your help! Have a great day :)

**Comment by benschwarz** [comment]
@Macleykun Glad to see you got this working. I was wondering if you had any commentary around how we could improve the README to make this easier to find? Was there a specific term that you were scanning for that could be added? 

Thanks for helping out @bazzadp 🙇

**Comment by Macleykun** [comment]
Sorry for the late reply, had alot of work and unreliable power for a bit.
Honestly thanks to the configuration example where checkout is used i noticed compressiononly was the key to what i looked for.
I think it's b/c i was put off by the pull request part that i looked futher.
It is possible to also push the changes, but i noticed with my automation that if someone pushes another commit to the repo, pushing the changes will result in being behind.

So in short, i think it's beter to leave the README as is, it's beter practise to use pull-requests as they are won't fail in the end, but can only result in conflicts.

One unrelated question. You know a place where i can ask about Github Workflows? I need to learn how to use caching to speed up the process as it takes minutes now.

Again sorry for the late reply, love the project btw! Any idea when avif is going to be supported? If possible at all? I'm already achieving avif performance with webp thanks to image-actions, but was just wondering :P

**Comment by benschwarz** [comment]
Thanks for your feedback here @Macleykun 🤗

AVIF is something I'd like to handle alongside the addition to format transcoding (take one format and produce x other formats), but we're tied up with other major project work atm so it'll be a while til I can circle back on that.

**Comment by Macleykun** [comment]
Ohh, i only though compressing AVIF futher, but converting would be amazing ngl!

I hope you and your team/community will be able to do this oneday, that would make for a perfect imagemanager* in my eyes in Github Workflows!
